routes/web.php
			Route::get('', ['as' => 'index', 'uses' => 'AlterarSenhaController@index']);
			Route::post('update', ['as' => 'update', 'uses' => 'AlterarSenhaController@update']);
		});

	});

	#Administrador
	Route::namespace('Administrador')->prefix('administrador')->name('administrador.')->group(function (){

		#Empresa
		Route::group(['prefix' => 'empresa', 'as' => 'empresa.'], function () {
			Route::get('', ['as' => 'index', 'uses' => 'CompanyController@index']);
			Route::get('novo', ['as' => 'create', 'uses' => 'CompanyController@create']);
			Route::post('store', ['as' => 'store', 'uses' => 'CompanyController@store']);
			Route::get('editar/{id}', ['as' => 'edit', 'uses' => 'CompanyController@edit']);
			Route::post('update/{id}', ['as' => 'update', 'uses' => 'CompanyController@update']);
			Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'CompanyController@destroy']);
			Route::post('test_connection', ['as' => 'testConnection', 'uses' => 'CompanyController@testConnection']);
		});

		#Usuários
		Route::group(['prefix' => 'usuarios', 'as' => 'usuarios.'], function () {
			Route::get('', ['as' => 'index', 'uses' => 'UsersController@index']);
			Route::get('novo', ['as' => 'create', 'uses' => 'UsersController@create']);
			Route::post('store', ['as' => 'store', 'uses' => 'UsersController@store']);
			Route::get('editar/{id}', ['as' => 'edit', 'uses' => 'UsersController@edit']);
			Route::post('update/{id}', ['as' => 'update', 'uses' => 'UsersController@update']);
			Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'UsersController@destroy']);
		});

		#Grupos
		Route::group(['prefix' => 'grupos', 'as' => 'grupos.'], function () {
			Route::get('', ['as' => 'index', 'uses' => 'GroupsController@index']);
			Route::get('novo', ['as' => 'create', 'uses' => 'GroupsController@create']);
			Route::post('store', ['as' => 'store', 'uses' => 'GroupsController@store']);
			Route::get('editar/{id}', ['as' => 'edit', 'uses' => 'GroupsController@edit']);
			Route::post('update/{id}', ['as' => 'update', 'uses' => 'GroupsController@update']);
			Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'GroupsController@destroy']);
		});




		#Menus UNI.T-S
		Route::prefix('menus-units')->name('menus-units.')->group(function (){
			Route::get('', 'MenuUnitsController@index')->name('index');
			Route::get('show/{id}', 'MenuUnitsController@show')->name('show');
			Route::post('create', 'MenuUnitsController@create')->name('create');
			Route::post('update', 'MenuUnitsController@update')->name('update');
			Route::post('update-order', 'MenuUnitsController@updateOrder')->name('update-order');
		});

	});

	#Ofensores
	Route::namespace('Offender')->group(function () {

		#Cadastros de Ofensores
		Route::resource('offender', 'OffenderController')->except('show');

		Route::prefix('offender')->name('offender.')->group(function (){

			#Detalhes do ofensor para o modal
			Route::get('show-details/{offender}', 'OffenderController@show_details')->name('show-details');

			#Auto completes dos filtros
			Route::get('search', 'OffenderController@search')->name('search');

			#Datatable
			Route::get('datatable', 'OffenderController@datatable')->name('datatable');

			#Download do arquivo
			Route::get('download/{file_id}', 'OffenderController@download')->name('download');

			#Remove File
			Route::get('remove-file/{file_id}', 'OffenderController@remove_file')->name('remove_file');

			#check offender id exists
			Route::get('offender-id-exists/{offender_id}', 'OffenderController@offender_id_exists')->name('offender_id_exists');

            #ação
            Route::get('action/{offender_id}', 'OffenderController@action')->name('action');
			/* ========================================================================================== */
			#Exportação
			Route::prefix('export')->name('export.')->group(function (){
				Route::get('', 'OffenderExportController@index')->name('index');
				Route::post('', 'OffenderExportController@export')->name('export');
			});

			/* ========================================================================================== */
			#Importação
			Route::prefix('import')->name('import.')->group(function (){
				Route::get('', 'OffenderImportController@index')->name('index');
				Route::get('log-download/{id}', 'OffenderImportController@log_download')->name('log-download');
				Route::post('', 'OffenderImportController@import')->name('import');
			});

			/* ========================================================================================== */
			#Notificações
			Route::get('notifications', 'OffenderController@notifications')->name('notifications');

			/* ========================================================================================== */
			#Historico
			Route::resource('history', 'OffenderHistoryController')->only(['index']);
			Route::prefix('history')->name('history.')->group(function (){

				#Detalhes do ofensor para o modal
				Route::get('show-details/{offender}', 'OffenderHistoryController@show_details')->name('show-details');

				#Datatable
				Route::get('datatable', 'OffenderHistoryController@datatable')->name('datatable');

				#Auto completes dos filtros
				Route::get('search', 'OffenderHistoryController@search')->name('search');

				#Exporta Busca do filtro
				Route::post('export', 'OffenderHistoryController@export')->name('export');
			});

			/* ========================================================================================== */
			#Sincronismo
			Route::resource('synchronism', 'OffenderSynchronismController')->except('show');
			Route::prefix('synchronism')->name('synchronism.')->group(function (){
				#Detalhes do ofensor para o modal
				Route::get('show-details/{offender}/{column?}', 'OffenderSynchronismController@show_details')->name('show-details');

				#Datatable
				Route::get('datatable', 'OffenderSynchronismController@datatable')->name('datatable');

				#Auto completes dos filtros
				Route::get('search', 'OffenderSynchronismController@search')->name('search');

				#getRow
				Route::get('get-row', 'OffenderSynchronismController@get_row')->name('get-row');
			});

		});

	});

	#Ferramentas
	Route::namespace('Session')->prefix('session')->name('session.')->group(function (){

		#Troca de empresa
		Route::any('company/choice', 'SessionController@companyChoice')->name('company.choice');

		#Trocar Lingua da aplicação
		Route::post('language/choice', 'SessionController@languageChoice')->name('language.choice');

	});

	# UNITS
	Route::namespace('Units')->group(function ()
	{
	
		Route::prefix('units')->name('units.')->group(function (){

			# DASHBOARD
			Route::prefix('dashboard')->name('dashboard.')->group(function (){
				Route::any('', 'UnitsDashboardController@index')->name('index');
				//Route::post('/charts', 'UnitsDashboardController@charts')->name('charts'); //teste
			});

			##Serviços
			Route::prefix('solicitacoes')->name('solicitacoes.')->group(function (){
				Route::get('index/{slug}', 'UnitsController@index')->where('slug', '([A-Za-z0-9\-\/]+)');
				Route::get('form/{slug}/{id}/{action?}', 'UnitsController@form')->where('slug', '([A-Za-z0-9\-\/]+)');
				Route::post('store', 'UnitsController@store')->name('store')->where('slug', '([A-Za-z0-9\-\/]+)');
			});

            # Segurança
            Route::prefix('seguranca')->name('security.')->group(function (){
                Route::get('usuarios_logados', 'UnitsLoggedUsersController@index')->name('logged_users.index');
                Route::post('logout', 'UnitsLoggedUsersController@logout')->name('logged_users.logout');
            });

            # Lista log atividades
            Route::get('log-atividades', 'UnitsActivitiesLogController@index')->name('activities_log.index');
            Route::get('log-atividades/datatable', 'UnitsActivitiesLogController@datatable')->name('activities_log.datatable');
            Route::get('log-atividades/search', 'UnitsActivitiesLogController@search')->name('activities_log.search');
            Route::get('log-atividades/show-details/{log_active_id}', 'UnitsActivitiesLogController@show_details')->name('activities_log.show-details');


            # Relatórios
            Route::prefix('relatorios')->name('relatorios.')->group(function (){
                Route::get('consulta-plataforma', 'UnitsReportController@index')->name('consulta-plataforma.index');
                Route::post('consulta-plataforma', 'UnitsReportController@search')->name('consulta-plataforma.search');

                #Relatório Analitico - Atendimentos UNI.T-S
                Route::get('atendimentos-units', 'Reports\AnalyticalAttendanceController@index')->name('atendimentos-units');
                Route::get('atendimentos-units/datatable', 'Reports\AnalyticalAttendanceController@datatable')->name('atendimentos-units.datatable');
                Route::post('atendimentos-units/export', 'Reports\AnalyticalAttendanceController@export')->name('atendimentos-units.export');
                Route::get('atendimentos-units/teste', 'Reports\AnalyticalAttendanceController@teste')->name('atendimentos-units.teste');

                #Compras VOD
                Route::get('compras_vod', 'Reports\UnitsVodShoppingController@comprasVod')->name('compras_vod');
                Route::get('compras_vod/datatable', 'Reports\UnitsVodShoppingController@datatable')->name('compras_vod.datatable');
                Route::post('compras_vod/export', 'Reports\UnitsVodShoppingController@export')->name('compras_vod.export');

            });


            # Busca de dados na base da NET
            Route::post('/net/buscar_assinante', 'UnitsNetController@getCustomer')->name('net.get_customer');
            Route::post('/net/buscar_terminal', 'UnitsNetController@getTerminal')->name('net.get_terminal');
            Route::post('/net/realizaMudança', 'UnitsNetController@change')->name('net.change');

		});
		
	});

});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/layouts/inc/breadcrumb.blade.php
@if(isset($breadcrumb) && is_array($breadcrumb))

    <div class="page-bar">
        <ul class="page-breadcrumb">
            {!! '<li><span>'.implode('</span><i class="fa fa-circle"></i></li><li><span>', $breadcrumb).'</i></li>' !!}
        </ul>
    </div>


@endif

resources/views/layouts/inc/footer.blade.php
<div class="page-footer">
    <div class="page-footer-inner">
        {{ date('Y') }} &copy; ART IT - <i>Intelligent Technology.</i>
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>

resources/views/layouts/inc/header.blade.php
<div class="page-header navbar navbar-fixed-top">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner ">
        <!-- BEGIN LOGO -->
        <div class="page-logo">
            <a href="{{ route('home') }}">
                <div class="caption logo-default">
                    <span class="caption-subject font-blue-steel bold uppercase"> {!! env('APP_NAME') !!}</span>
                </div>
            </a>
            <div class="menu-toggler sidebar-toggler">
                <span></span>
            </div>
        </div>
        <!-- END LOGO -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
            <span></span>
        </a>
        <!-- END RESPONSIVE MENU TOGGLER -->
        <!-- BEGIN TOP NAVIGATION MENU -->
        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">
            @php
                $totalNotifications = auth()->user()->unreadNotifications->count();
            @endphp
            @if($totalNotifications)
                <!-- BEGIN NOTIFICATION DROPDOWN -->
                <li class="dropdown dropdown-extended dropdown-notification" id="header_notification_bar">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <i class="icon-bell"></i>
                        <span class="badge badge-default"> {{$totalNotifications}} </span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="external">
                            <h3>
                                <span class="bold">Notificações</span> pendentes
                            </h3>
                        </li>
                        <li>
                            <ul class="dropdown-menu-list scroller" style="height: 250px;" data-handle-color="#637283">
                                @foreach(auth()->user()->unreadNotifications as $notification)
                                <li>
                                    <a href="{{ route('offender.edit', $notification->data['offender_id']) }}" data-id="{{ $notification->id }}" class="read_notification">
                                        <span class="details">
                                            <span class="label label-sm label-icon label-warning">
                                                <i class="fa fa-bell-o"></i>
                                            </span> {{ $notification->data['message'] }}
                                        </span>
                                    </a>
                                </li>
                                @endforeach
                            </ul>
                        </li>
                    </ul>
                </li>
            @endif
                <!-- END NOTIFICATION DROPDOWN -->

                <!-- BEGIN COMPANY BAR -->

                @if(config('sys.show_company'))

                    <li class="dropdown dropdown-language">

                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <i class="fa fa-bank"></i>
                            <span class="langname"><small>{{Lang::get('sys.header.company')}}:</small> <b>{{session('company')['name']}}</b> </span>

                            @if(Auth::user()->isAdmin() && session('companies')->count() > 1)
                                <i class="fa fa-angle-down"></i>
                            @else
                                &nbsp;&nbsp;
                            @endif

                        </a>

                        @if(Auth::user()->isAdmin() && session('companies')->count() > 1)

                            <ul class="dropdown-menu dropdown-menu-default">

                                @foreach(session('companies') as $company)

                                    @if($company->id != session('company')['id'])

                                        <li>
                                            <a href="javascript:;" onclick="event.preventDefault(); document.getElementById('choice-form-{{$company->id}}').submit();">
                                                {{$company->description}}
                                            </a>

                                            {!! Form::open(['route' => 'session.company.choice', 'method' => 'post', 'id'=> 'choice-form-'.$company->id, 'style'=>'display: none;']) !!}

                                            {!! Form::hidden('id', $company->id) !!}

                                            {!! Form::close() !!}
                                        </li>

                                    @endif

                                @endforeach

                            </ul>

                        @endif

                    </li>

            @endif

            <!-- END COMPANY BAR -->

                <!-- BEGIN USER LOGIN DROPDOWN -->
                <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                <li class="dropdown dropdown-user">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <i class="fa fa-user"></i>
                        <span class="langname"><small>{{Lang::get('sys.header.user')}}:</small> <b>{{ Auth::user()->name}}</b></span>
                        <i class="fa fa-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-default">
                        <li>

                            <a href="{{ url('/logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                <i class="icon-logout"></i>&nbsp;&nbsp;&nbsp;{{Lang::get('sys.header.logout')}}
                            </a>

                            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>

                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END HEADER INNER -->
</div>

resources/views/layouts/inc/nav.blade.php
<ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
  <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
  <li class="sidebar-toggler-wrapper hide">
    <div class="sidebar-toggler">
        <span></span>
    </div>
  </li>
  <!-- END SIDEBAR TOGGLER BUTTON -->
  {{--Home--}}
  <li class="nav-item start {{ (request()->is('home*')) ? 'active open' : '' }}">
    <a href="{{ route('home') }}" class="nav-link nav-toggle">
      <i class="icon-home"></i>
      <span class="title">Dashboard</span>
    </a>
  </li>

  @if(Gate::allows('company_list') || Gate::allows('company_edit') || Gate::allows('user_list') || Gate::allows('group_list'))
    <li class="nav-item start {{ (request()->is('administrador*')) ? 'active open' : '' }}">
      <a href="javascript:;" class="nav-link nav-toggle">
        <i class="icon-lock"></i>
        <span class="title">{{Lang::get('sys.menu.administrador.administrador')}}</span>
        <span class="selected"></span>
        <span class="arrow {{ (request()->is('administrador*')) ? 'active open' : '' }}"></span>
      </a>

      <ul class="sub-menu">
        @if(Gate::allows('company_list') || Gate::allows('company_edit'))
          <li class="nav-item {{ (request()->is('administrador/empresa*')) ? 'active open' : '' }}">
            <a href="{{route('administrador.empresa.index')}}">
              <span class="title">{{Lang::get('sys.menu.administrador.empresas')}}</span>
            </a>
          </li>
        @endif

        @can('user_list')
          <li class="nav-item {{ (request()->is('administrador/usuarios*')) ? 'active open' : '' }}">
            <a href="{{route('administrador.usuarios.index')}}">
              <span class="title">{{Lang::get('sys.menu.administrador.usuarios')}}</span>
            </a>
          </li>
        @endcan

        @can('group_list')
          <li class="nav-item {{ (request()->is('administrador/grupos*')) ? 'active open' : '' }}">
            <a href="{{route('administrador.grupos.index')}}">
              <span class="title">{{Lang::get('sys.menu.administrador.grupos')}}</span>
            </a>
          </li>
        @endcan

        @can('group_list')
          <li class="nav-item {{ (request()->is('administrador/menus-units*')) ? 'active open' : '' }}">
            <a href="{{route('administrador.menus-units.index')}}">
              <span class="title">{{Lang::get('sys.menu.administrador.menus_units')}}</span>
            </a>
          </li>
        @endcan
      </ul>
    </li>
  @endif

  {{--Ofensores--}}
  @if(Gate::allows('offender_list'))
  <li class="nav-item {{ (request()->is('offender*')) ? 'active open' : '' }}">
    <a href="javascript:;" class="nav-link nav-toggle">
      <i class="icon-feed"></i>
      <span class="title">{{Lang::get('sys.menu.ofensores.ofensores')}}</span>
      <span class="arrow"></span>
    </a>
    <ul class="sub-menu">

      {{--Ofensores--}}
      @can('offender_list')
      <li class="nav-item {{ (request()->is('offender')) ? 'active open' : '' }}">
        <a href="{{ route('offender.index') }}" class="nav-link ">
          <span class="title">{{Lang::get('sys.menu.ofensores.ofensores')}}</span>
        </a>
      </li>
      @endcan

      {{--Sincronismo--}}
      @can('synchronism_list')
        <li class="nav-item {{ (request()->is('offender/synchronism')) ? 'active open' : '' }}">
          <a href="{{ route('offender.synchronism.index') }}" class="nav-link ">
            <span class="title">{{Lang::get('sys.menu.ofensores.sincronismo')}}</span>
          </a>
        </li>
      @endcan

      {{--Extração de Dados--}}
      @can('offender_list')
      <li class="nav-item {{ (request()->is('offender/export')) ? 'active open' : '' }}">
        <a href="{{ route('offender.export.index') }}" class="nav-link ">
          <span class="title">{{Lang::get('sys.menu.ofensores.extracao_dados')}}</span>
        </a>
      </li>
      @endcan

      {{--Carga de Dados--}}
      @can('offender_import')
      <li class="nav-item {{ (request()->is('offender/import')) ? 'active open' : '' }}">
        <a href="{{ route('offender.import.index') }}" class="nav-link ">
          <span class="title">{{Lang::get('sys.menu.ofensores.carga_dados')}}</span>
        </a>
      </li>
      @endcan

      {{--Histórico--}}
      @can('offender_list')
      <li class="nav-item  {{ (request()->is('offender/history')) ? 'active open' : '' }}">
        <a href="{{ route('offender.history.index') }}" class="nav-link ">
          <span class="title">{{Lang::get('sys.menu.ofensores.historico')}}</span>
        </a>
      </li>
      @endcan
    </ul>
  </li>
  @endif

  {{--Units--}}
  @if(Gate::allows('units_dashboard'))

    @include('administrador.menu_units.nav')

  @endif 
</ul>