routes/web.php
<?php

Route::get('/', function () {
    return redirect()->route('home');
});

Auth::routes();
//, 'auth.unique.user'
Route::middleware(['auth', 'translate'])->group(function () {
//Route::middleware(['translate'])->group(function () {

	#Dashboard
	Route::get('/home', 'HomeController@index')->name('home');
	Route::get('/read_notification/{id}', 'HomeController@read_notification')->name('read_notification');


	Route::group(['prefix' => 'perfil', 'as' => 'perfil.', 'namespace' => 'Perfil'], function () {

		Route::group(['prefix' => 'alterar_senha', 'as' => 'alterar_senha.'], function () {
			Route::get('', ['as' => 'index', 'uses' => 'AlterarSenhaController@index']);
			Route::post('update', ['as' => 'update', 'uses' => 'AlterarSenhaController@update']);
		});

	});

	#Administrador
	Route::namespace('Administrador')->prefix('administrador')->name('administrador.')->group(function (){

		#Empresa
		Route::group(['prefix' => 'empresa', 'as' => 'empresa.'], function () {
			Route::get('', ['as' => 'index', 'uses' => 'CompanyController@index']);
			Route::get('novo', ['as' => 'create', 'uses' => 'CompanyController@create']);
			Route::post('store', ['as' => 'store', 'uses' => 'CompanyController@store']);
			Route::get('editar/{id}', ['as' => 'edit', 'uses' => 'CompanyController@edit']);
			Route::post('update/{id}', ['as' => 'update', 'uses' => 'CompanyController@update']);
			Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'CompanyController@destroy']);
			Route::post('test_connection', ['as' => 'testConnection', 'uses' => 'CompanyController@testConnection']);
		});

		#Usuários
		Route::group(['prefix' => 'usuarios', 'as' => 'usuarios.'], function () {
			Route::get('', ['as' => 'index', 'uses' => 'UsersController@index']);
			Route::get('novo', ['as' => 'create', 'uses' => 'UsersController@create']);
			Route::post('store', ['as' => 'store', 'uses' => 'UsersController@store']);
			Route::get('editar/{id}', ['as' => 'edit', 'uses' => 'UsersController@edit']);
			Route::post('update/{id}', ['as' => 'update', 'uses' => 'UsersController@update']);
			Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'UsersController@destroy']);
		});

		#Grupos
		Route::group(['prefix' => 'grupos', 'as' => 'grupos.'], function () {
			Route::get('', ['as' => 'index', 'uses' => 'GroupsController@index']);
			Route::get('novo', ['as' => 'create', 'uses' => 'GroupsController@create']);
			Route::post('store', ['as' => 'store', 'uses' => 'GroupsController@store']);
			Route::get('editar/{id}', ['as' => 'edit', 'uses' => 'GroupsController@edit']);
			Route::post('update/{id}', ['as' => 'update', 'uses' => 'GroupsController@update']);
			Route::get('destroy/{id}', ['as' => 'destroy', 'uses' => 'GroupsController@destroy']);
		});




		#Menus UNI.T-S
		Route::prefix('menus-units')->name('menus-units.')->group(function (){
			Route::get('', 'MenuUnitsController@index')->name('index');
			Route::get('show/{id}', 'MenuUnitsController@show')->name('show');
			Route::post('create', 'MenuUnitsController@create')->name('create');
			Route::post('update', 'MenuUnitsController@update')->name('update');
			Route::post('update-order', 'MenuUnitsController@updateOrder')->name('update-order');
		});

	});

	#Ofensores
	Route::namespace('Offender')->group(function () {

		#Cadastros de Ofensores
		Route::resource('offender', 'OffenderController')->except('show');

		Route::prefix('offender')->name('offender.')->group(function (){

			#Detalhes do ofensor para o modal
			Route::get('show-details/{offender}', 'OffenderController@show_details')->name('show-details');

			#Auto completes dos filtros
			Route::get('search', 'OffenderController@search')->name('search');

			#Datatable
			Route::get('datatable', 'OffenderController@datatable')->name('datatable');

			#Download do arquivo
			Route::get('download/{file_id}', 'OffenderController@download')->name('download');

			#Remove File
			Route::get('remove-file/{file_id}', 'OffenderController@remove_file')->name('remove_file');

			#check offender id exists
			Route::get('offender-id-exists/{offender_id}', 'OffenderController@offender_id_exists')->name('offender_id_exists');

            #ação
            Route::get('action/{offender_id}', 'OffenderController@action')->name('action');
			/* ========================================================================================== */
			#Exportação
			Route::prefix('export')->name('export.')->group(function (){
				Route::get('', 'OffenderExportController@index')->name('index');
				Route::post('', 'OffenderExportController@export')->name('export');
			});

			/* ========================================================================================== */
			#Importação
			Route::prefix('import')->name('import.')->group(function (){
				Route::get('', 'OffenderImportController@index')->name('index');
				Route::get('log-download/{id}', 'OffenderImportController@log_download')->name('log-download');
				Route::post('', 'OffenderImportController@import')->name('import');
			});

			/* ========================================================================================== */
			#Notificações
			Route::get('notifications', 'OffenderController@notifications')->name('notifications');

			/* ========================================================================================== */
			#Historico
			Route::resource('history', 'OffenderHistoryController')->only(['index']);
			Route::prefix('history')->name('history.')->group(function (){

				#Detalhes do ofensor para o modal
				Route::get('show-details/{offender}', 'OffenderHistoryController@show_details')->name('show-details');

				#Datatable
				Route::get('datatable', 'OffenderHistoryController@datatable')->name('datatable');

				#Auto completes dos filtros
				Route::get('search', 'OffenderHistoryController@search')->name('search');

				#Exporta Busca do filtro
				Route::post('export', 'OffenderHistoryController@export')->name('export');
			});

			/* ========================================================================================== */
			#Sincronismo
			Route::resource('synchronism', 'OffenderSynchronismController')->except('show');
			Route::prefix('synchronism')->name('synchronism.')->group(function (){
				#Detalhes do ofensor para o modal
				Route::get('show-details/{offender}/{column?}', 'OffenderSynchronismController@show_details')->name('show-details');

				#Datatable
				Route::get('datatable', 'OffenderSynchronismController@datatable')->name('datatable');

				#Auto completes dos filtros
				Route::get('search', 'OffenderSynchronismController@search')->name('search');

				#getRow
				Route::get('get-row', 'OffenderSynchronismController@get_row')->name('get-row');
			});

		});

	});

	#Ferramentas
	Route::namespace('Session')->prefix('session')->name('session.')->group(function (){

		#Troca de empresa
		Route::any('company/choice', 'SessionController@companyChoice')->name('company.choice');

		#Trocar Lingua da aplicação
		Route::post('language/choice', 'SessionController@languageChoice')->name('language.choice');

	});

	# UNITS
	Route::namespace('Units')->group(function ()
	{
	
		Route::prefix('units')->name('units.')->group(function (){

			# DASHBOARD
			Route::prefix('dashboard')->name('dashboard.')->group(function (){
				Route::any('', 'UnitsDashboardController@index')->name('index');
				//Route::post('/charts', 'UnitsDashboardController@charts')->name('charts'); //teste
			});

			##Serviços
			Route::prefix('solicitacoes')->name('solicitacoes.')->group(function (){
				Route::get('index/{slug}', 'UnitsController@index')->where('slug', '([A-Za-z0-9\-\/]+)');
				Route::get('form/{slug}/{id}/{action?}', 'UnitsController@form')->where('slug', '([A-Za-z0-9\-\/]+)');
				Route::post('store', 'UnitsController@store')->name('store')->where('slug', '([A-Za-z0-9\-\/]+)');
			});

            # Segurança
            Route::prefix('seguranca')->name('security.')->group(function (){
                Route::get('usuarios_logados', 'UnitsLoggedUsersController@index')->name('logged_users.index');
                Route::post('logout', 'UnitsLoggedUsersController@logout')->name('logged_users.logout');
            });

            # Lista log atividades
            Route::get('log-atividades', 'UnitsActivitiesLogController@index')->name('activities_log.index');
            Route::get('log-atividades/datatable', 'UnitsActivitiesLogController@datatable')->name('activities_log.datatable');
            Route::get('log-atividades/search', 'UnitsActivitiesLogController@search')->name('activities_log.search');
            Route::get('log-atividades/show-details/{log_active_id}', 'UnitsActivitiesLogController@show_details')->name('activities_log.show-details');


            # Relatórios
            Route::prefix('relatorios')->name('relatorios.')->group(function (){
                Route::get('consulta-plataforma', 'UnitsReportController@index')->name('consulta-plataforma.index');
                Route::post('consulta-plataforma', 'UnitsReportController@search')->name('consulta-plataforma.search');

                #Relatório Analitico - Atendimentos UNI.T-S
                Route::get('atendimentos-units', 'Reports\AnalyticalAttendanceController@index')->name('atendimentos-units');
                Route::get('atendimentos-units/datatable', 'Reports\AnalyticalAttendanceController@datatable')->name('atendimentos-units.datatable');
                Route::post('atendimentos-units/export', 'Reports\AnalyticalAttendanceController@export')->name('atendimentos-units.export');
                Route::get('atendimentos-units/teste', 'Reports\AnalyticalAttendanceController@teste')->name('atendimentos-units.teste');

                #Compras VOD
                Route::get('compras_vod', 'Reports\UnitsVodShoppingController@comprasVod')->name('compras_vod');
                Route::get('compras_vod/datatable', 'Reports\UnitsVodShoppingController@datatable')->name('compras_vod.datatable');

app/Models/Units/ReportModels.php
<?php


namespace App\Models\Units;


class ReportModels
{
    const VOD_TYPES = [
        'SVOD_NET' => 'SVOD NET',
        'TVOD_NET' => 'TVOD NET',
        'NW_SVOD' => 'NOWONLINE SVOD NET',
        'NW_NET' => 'NOWONLINE TVOD NET',
        'TVOD_CLARO' => 'TVOD CLARO',
    ];

    const STATUS = [
        'OK' => 'Processado OK',
        'NOK' => 'Processamento Pendente',
    ];
}

app/Models/Units/UnitsMenuOrder.php
<?php

namespace App\Models\Units;

use App\Http\Traits\CompanyTrait;
use Illuminate\Database\Eloquent\Model;

class UnitsMenuOrder extends Model
{

	use CompanyTrait;

    protected $fillable = ['menu_order', 'company_id'];

}

app/Http/Controllers/Units/Reports/AnalyticalAttendanceController.php
<?php

namespace App\Http\Controllers\Units\Reports;

use App\Exports\Units\AnalyticalAttendanceExport;
use App\Services\Units\Reports\AnalyticalAttendanceService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AnalyticalAttendanceController extends Controller
{

    /**
     * @var AnalyticalAttendanceService
     */
    private $attendanceService;

    public function __construct(AnalyticalAttendanceService $attendanceService)
    {
        $this->attendanceService = $attendanceService;
    }

    public function index()
    {

        $status = [
            ''      => 'TODOS',
            'F'    => 'Sucesso',
            'E'   => 'Erro',
        ];

        return view('units.reports.analytical_attendance.index', compact( 'status'));

    }


    public function datatable(Request $request)
    {
        if ($request->ajax()) {
            return $this->attendanceService->datatable($request);
        }
        return redirect()->route('units.relatorios.atendimentos-units ');
    }

    public function export(Request $request)
    {
        $list = (object) $this->attendanceService->getData($request);
        return (new AnalyticalAttendanceExport($list))->download('Relatório_Analitico_.xlsx');
    }

}

app/Http/Controllers/Units/Reports/UnitsVodShoppingController.php
<?php


namespace App\Http\Controllers\Units\Reports;

use App\Exports\Units\VodShoppingExport;
use App\Services\Units\Reports\VodShoppingService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class UnitsVodShoppingController
{

    /**
     * @var VodShoppingService
     */
    private $vodShoppingService;

    public function __construct(VodShoppingService $vodShoppingService)
    {
        $this->vodShoppingService = $vodShoppingService;
    }

    public function comprasVod()
    {

        $types =  [
            'SVOD_NET'      => 'SVOD NET',
            'TVOD_NET'      => 'TVOD NET',
            'NW_SVOD'       => 'NOWONLINE SVOD NET',
            'NW_NET'        => 'NOWONLINE TVOD NET',
            'TVOD_CLARO'    => 'TVOD CLARO',
        ];

        $status = [
            ''      => 'TODOS',
            'OK'    => 'Processado OK',
            'NOK'   => 'Processamento Pendente',
        ];

        return view('units.reports.vod_shopping.index', compact('types', 'status'));

    }


    public function datatable(Request $request)
    {
        if ($request->ajax()) {
            return $this->vodShoppingService->datatable($request);
        }
        return redirect()->route('units.relatorios.compras_vod ');
    }

    public function export(Request $request)
    {
        $list = $this->vodShoppingService->getSelect($request);
        return (new VodShoppingExport($list))->download('Compras_VOD.xlsx');
    }

}

app/Http/Controllers/Units/UNitsNetController.php
<?php

namespace App\Http\Controllers\Units;

use App\Http\Controllers\Controller;
use App\Services\Units\UnitsNetService;
use Illuminate\Http\Request;

class UnitsNetController extends Controller {

    private $unitsNetService;

    public function __construct(UnitsNetService $unitsNetService)
    {
        $this->unitsNetService = $unitsNetService;
    }

    public function getCustomer(Request $request)
    {
        try{

            $input = $request->all();
            if ($input['operadora'] == '21') {
                $base_claro = True;
            } else {
                $base_claro = False;
            }

            $data = $this->unitsNetService->buscaAssinante($input['operadora'], $input['contrato'], $base_claro);

            if(!$data){
                return response()->json(['message' => 'Contrato inválido ou não pertence a cidade informada.'], 400);
            }

            return response()->json(['success'=>'Ok', 'data' => $data]);
        } catch(\Exception $e){
            // TODO: Qual mensagem exibir para o usuário em caso de falha de conexão com a base de dados da net/claro?
            return response()->json(['error' => $e->getMessage(), 'message' => 'Erro de conexão com o banco de dados.']);

        }
    }

    public function getTerminal(Request $request)
    {
        try {
            $dados = $request->all();
            $dados['ddd'] = substr($dados["terminal"], 0, 2);
            $dados['telefone'] = substr($dados["terminal"], 2, 9);

            $data = $this->unitsNetService->buscaDadosTerminal($dados['operadora'],$dados['ddd'],$dados['telefone']);

            if (count($data) == 0 || !$data) {
                return response()->json(['message' => 'Telefone não encontrado'], 400);
            }

            return response()->json(['success' => 'Ok', 'data' => $data]);

        } catch(\Exception $e) {
            return response()->json(['error' => $e->getMessage(), 'message' => 'Erro de conexão com o banco de dados.']);
        }
    }
}

app/Http/Controllers/Units/UnitsActivitiesLogController.php
<?php

namespace App\Http\Controllers\Units;

use App\Models\Units\UnitsSolicitation;
use App\Services\Units\UnitsAcitivitiesLogService;
use App\Models\Units\UnitsService;
use App\Models\Units\UnitsMenu;
use App\Models\User;
use App\Services\Units\UnitsSolicitationService;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UnitsActivitiesLogController extends Controller
{

    private $unitsActivitiesLogService;
    private $unitsService;
    private $unitsMenu;
    private $user;

    public function __construct(
        UnitsAcitivitiesLogService $unitsActivitiesLogService,
        UnitsService $unitsService,
        UnitsMenu $unitsMenu,
        User $user
    )
    {
        $this->unitsActivitiesLogService = $unitsActivitiesLogService;
        $this->unitsService = $unitsService;
        $this->unitsMenu = $unitsMenu;
        $this->user = $user;
    }

    public function index()
    {
       $this->authorize('units_activities_log_list');
       $unitsServices = $this->unitsService->get();
       $users = $this->user->orderBy('username')->pluck('username','username')->toArray();

       foreach ($unitsServices as $service) {

           if(!empty($service->slug)){
               $menu = $this->unitsMenu->bySlug($service->slug)->first();
               if($menu){
                   $services[ $service->id ] = strtoupper($menu['title'] . ' - ' . $service->description);
               }
           }else{
               $services[ $service->id ] = strtoupper($service->description);
           }
       }

       asort($services);

       return view('units.units_log_activities.index', compact('services','users'));
    }

    public function search(Request $request)
    {
        echo $this->unitsActivitiesLogService->search($request->all());
    }

    public function show_details($id)
    {
        $log_activities = UnitsSolicitation::find($id);
        if ($log_activities)
            return view('units.units_log_activities.modal', compact('log_activities'))->render();

        return false;
    }


    public function datatable(Request $request)
    {
        if ($request->ajax()) {
            return $this->unitsActivitiesLogService->datatable($request);
        }
        return redirect()->route('units.index');
    }

}

resources/views/units/units_logged_users/index.blade.php
@extends('layouts.app', [
    'breadcrumb' => ['Units', 'Segurança', 'Usuários Logados'],
    'page_title' => 'Segurança',
    'page_title_small' => 'Usuários Logados'
])


@push('css')
  {{-- autocomplete --}}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  {{--Date picker--}}
  <link href="{{ asset('assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css') }}" rel="stylesheet" type="text/css" />
  <link href="{{ asset('assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css') }}" rel="stylesheet" type="text/css" />

  {{--boostrap-table--}}
  <link href="{{ asset('assets/global/plugins/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
  <link href="{{ asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css') }}" rel="stylesheet" type="text/css" />

  {{--modal--}}
  <link href="{{ asset('assets/global/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css') }}" rel="stylesheet" type="text/css" />
  <link href="{{ asset('assets/global/plugins/bootstrap-modal/css/bootstrap-modal.css') }}" rel="stylesheet" type="text/css" />
@endpush

@section('content')

  <div class="row">
    <div class="col-sm-12">
      <p>Usuários logados</p>


      {{--Listagem--}}
      <table class="table table-striped table-hover" id="logged-table">
        <thead>
        <tr>
          <th>Usuário</th>
          <th>Empresa</th>
          <th>IP</th>
          <th>Navegador</th>
          <th>Última ação</th>
          <th class="text-center" style="width: 85px;">Ações</th>
        </tr>
        </thead>
        <tbody>
{{--        {{dd($logged[0]->session)}}--}}
          @foreach($logged as $user)
            <tr>
              <td>{{ $user->name }}</td>
              <td>{{ $user->company->description }}</td>
              <td>{{ $user->session->ip_address }}</td>
              <td>{{ $user->session->user_agent }}</td>
              <td>{{ $user->session->last_activity }}</td>
              <td>
                <button class="btn btn-success loggout" data-id="{{ $user->id }}">Deslogar</button>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
      @endsection

      @push('js')
        <script>
          $(".loggout").on('click', function() {
            $.ajax({
              type: 'POST',
              headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
              },
              url:'/units/seguranca/logout',
              data:{'id': $(this).attr('data-id')},
              timeout: 15000,
              beforeSend: function (xhr, settings) {
                $(".loading-fs").show();
              },
              success:function(response){
                window.location.href = "{{ route('units.security.logged_users.index') }}";
              },
              complete: function () {
                $(".loading-fs").hide();
              },
              error: function(response, timeout){
                $(".loading-fs").hide();
              }
            });
          });
        </script>
        {{--autocomplete--}}
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

        {{--boostrap-table--}}
        <script src="{{ asset('assets/global/scripts/datatable.js') }}" type="text/javascript"></script>
        <script src="{{ asset('assets/global/plugins/datatables/datatables.min.js') }}" type="text/javascript"></script>
        <script src="{{ asset('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js') }}" type="text/javascript"></script>

        {{--modal--}}
        <script src="{{ asset('assets/global/plugins/bootstrap-modal/js/bootstrap-modalmanager.js') }}" type="text/javascript"></script>
        <script src="{{ asset('assets/global/plugins/bootstrap-modal/js/bootstrap-modal.js') }}" type="text/javascript"></script>

        {{--Maskinput--}}
        <script src="{{ asset('assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js') }}" type="text/javascript"></script>

        {{--date picker--}}
        <script src="{{ asset('assets/global/plugins/moment.min.js') }}" type="text/javascript"></script>
        <script src="{{ asset('assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js') }}" type="text/javascript"></script>
        <script src="{{ asset('assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}" type="text/javascript"></script>

        {{--scripts para a pagina--}}
        <script>
          $(function() {
            $("#logged-table").DataTable({
              "language": {
                "sEmptyTable": "Nenhum registro encontrado",
                "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                "sInfoPostFix": "",
                "sInfoThousands": ".",
                "sLengthMenu": "_MENU_ resultados por página",
                "sLoadingRecords": "Carregando...",
                "sProcessing": "Processando...",
                "sZeroRecords": "Nenhum registro encontrado",
                "sSearch": "Pesquisar",
                "oPaginate": {
                  "sNext": "Próximo",
                  "sPrevious": "Anterior",
                  "sFirst": "Primeiro",
                  "sLast": "Último"
                },
                "oAria": {
                  "sSortAscending": ": Ordenar colunas de forma ascendente",
                  "sSortDescending": ": Ordenar colunas de forma descendente"
                }
              }
            });
          });

        </script>

      @endpush

    </div>
  </div>

@push('js')
@endpush